//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class mainUsers
    {
        public string Id_Name { get; set; }
        public string FirstName { get; set; }
        public string SurrName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string rootPass { get; set; }
    }
}
